-- MySQL Script generated by MySQL Workbench
-- Sat Jan 12 18:40:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PAI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PAI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PAI` DEFAULT CHARACTER SET utf8 ;
USE `PAI` ;

-- -----------------------------------------------------
-- Table `PAI`.`studenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAI`.`studenti` (
  `idstudenti` INT NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(45) NULL,
  `prenume` VARCHAR(45) NULL,
  `grupa` VARCHAR(45) NULL,
  PRIMARY KEY (`idstudenti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAI`.`subiecte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAI`.`subiecte` (
  `idsubiecte` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(45) NULL,
  `nr_intrebari` VARCHAR(45) NULL,
  PRIMARY KEY (`idsubiecte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAI`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAI`.`Disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `dataExamen` DATE NULL,
  `puncteCredit` INT NULL,
  `studenti_idstudenti` INT NOT NULL,
  `subiecte_idsubiecte` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX `fk_Disciplina_studenti_idx` (`studenti_idstudenti` ASC) ,
  INDEX `fk_Disciplina_subiecte_idx` (`subiecte_idsubiecte` ASC) ,
  CONSTRAINT `fk_Disciplina_studenti`
    FOREIGN KEY (`studenti_idstudenti`)
    REFERENCES `PAI`.`studenti` (`idstudenti`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_subiecte`
    FOREIGN KEY (`subiecte_idsubiecte`)
    REFERENCES `PAI`.`subiecte` (`idsubiecte`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
